export const infodata = [
  {
    id: "about",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topline: "About Me",
    headline: "Full Stack Developer",
    description:
      "Hello! I am a full-stack developer with 4+ years of experience designing, implementing, and deploying conventional web, automation, report generation, and notification applications, ETL processes, RESTful services, and cross-platform mobile applications utilizing technologies like Java, Dart/Flutter, HTML, CSS, JavaScript, ReactJS and Spring Boot with SQL and NoSQL databases. Additionally, I have nearly 2 years of experience consulting clients based on acceptance criteria, rules, database design, 3rd party APIs, server requirements, and system architecture.",
    buttonLabel: "See My Work",
    primary: true,
    darkText: false,
    dark: false,
    redirect: "portfolio",
    smooth: true,
    btnLink: false,
  },
  {
    id: "portfolio",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topline: "Portfolio",
    headline: "My Projects",
    description: "",
    buttonLabel: "Get in touch",
    primary: true,
    darkText: true,
    dark: true,
    redirect: "/contactus",
    smooth: false,
    card: true,
    btnLink: true,
  },
];
